# Determines if we search the title (optional). Defaults to true.
matchTitle: false

# Determines if we search the body (optional). Defaults to true.
matchBody: true

# Determines if label matching is case sensitive (optional). Defaults to true.
caseSensitive: false

# Explicit keyword mappings to labels. Form of match:label. Required.
labelMappings:
    "[BUG - CRITICAL]": c-bug-critical
    "[CRITICAL]": c-bug-critical
    "[BUG - MAJOR]": c-bug-major
    "[MAJOR]": c-bug-major
    "[BUG]": c-bug
    "[FIX]": c-bug
    "[BUGFIX]": c-bug
    "fixes #": c-bug
    "[BUG - MINOR]": c-bug-minor
    "[MINOR]": c-bug-minor
    "[BUG - TRIVIAL]": c-bug-trivial
    "[TRIVIAL]": c-bug-trivial
    "[RUNTIME]": c-runtime
    "[INPUT WANTED]": e-input-wanted
    "[INPUT]": e-input-wanted
    "[FEEDBACK]": e-input-wanted
    "[ENHANCEMENT]": c-feature
    "[FEATURE]": c-feature
    "[FEAT]": c-feature
    "[BALANCE]": a-balance
    "[CLEANLINESS]": c-code-quality
    "[CODE QUALITY]": c-code-quality
    "[CLEAN]": c-code-quality
    "[CHORE]": c-code-quality
    "[EXPERIMENTAL]": c-experimental
    "[PERFORMANCE]": c-performance
    "[PERF]": c-performance
    "[QOL]": c-QoL
    "[REMOVAL]": c-removal
    "[REVERT]": c-revert
    "[REWORK]": c-rework
    "[SECRET]": a-secret
    "[TGUI]": c-ui
    "[UI]": c-ui
    "[TOOLS]": a-tooling
    "[TOOLING]": a-tooling
    "[EASY]": e-good-first-issue
    "[GFI]": e-good-first-issue
    "[GOOD FIRST ISSUE]": e-good-first-issue
    "[MEDAL]": a-medal
    "[WIKI]": e-add-to-wiki
    "[ADD TO WIKI]": e-add-to-wiki
    "[CONTEST]": e-contest
