# Add 'sprites' label to any changes within 'icons' folder or any subfolders
sprites:
  - icons/**/*
  
# Add 'mapping' label to any changes within 'maps' folder or any subfolders
mapping:
  - maps/**/*

# Add 'documentation' label to any changes to a .md file
documentation:
  - *.md
  
# Add 'github' label to any changes to the .github folder or any subfolders
github:
  - .github/**/*
