name: Final Review Labeler
on:
  pull_request_review:
    types: [submitted]

permissions:
  issues: write
  pull-requests: write

jobs:
  approve-labeler:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/graphql-action@v2.x
        id: get_approvals
        with:
          query: |
            query ($owner: String!, $repo: String!, $prNumber: Int!) {
              repository(owner: $owner, name: $repo) {
                pullRequest(number: $prNumber) {
                  reviews(states: APPROVED) {
                    totalCount
                  }
                }
              }
            }
          variables: |
            owner: ${{ github.event.repository.owner.login }}
            repo: ${{ github.event.repository.name }}
            prNumber: ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.PR_WRITE_PAT }}

      - uses: actions/github-script@v6
        with:
          script: |
            const result = JSON.parse(JSON.stringify(${{ steps.get_approvals.outputs.data }}))
            if (result.repository.pullRequest.reviews.totalCount >= 2) {
              github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['S-Ready-For-Final-Review']
              })
            }
          github-token: ${{ secrets.PR_WRITE_PAT }}
