name: update-changelog
on:
  pull_request:
    branches: [ master ]
    types: [ closed ]

jobs:
  update-changelog:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Get The Script
      run: |
        wget "https://raw.githubusercontent.com/${{ github.respoitory }}/master/.github/update_changelog.py"
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygithub
    - name: Update Changelog
      run: |
        python .github/update_changelog.py
      env:
        REPO: ${{ github.repository }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUM: ${{ github.event.number }}
        CHANGELOG_PATH: strings/changelog.txt
